# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.TextField(default='old_vid'),
            preserve_default=False,
        ),
    ]
