# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='SoundcloudSong',
        ),
        migrations.DeleteModel(
            name='SpotifySong',
        ),
        migrations.DeleteModel(
            name='YouTubeSong',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
